theme: jekyll-theme-chirpy

lang: en

timezone: Asia/Manila

title: Allen Sandiego

tagline: Software Developer • Engineer • Problem Solver

description: >-
  Seasoned Technology Professional specializing in the Oracle ecosystem,
  with deep functional and technical expertise across key enterprise platforms.

url: "https://www.allensandiego.com"

github:
  username: allensandiego

twitter:
  username: allensandiego

social:
  name: Allen Sandiego
  email: contact@allensandiego.com
  links:
    - https://twitter.com/allensandiego
    - https://github.com/allensandiego
    - https://www.linkedin.com/in/allensandiego/

webmaster_verifications:
  facebook: vng1rahcsd8i30bx1z2il53s0i1wp9

# Web Analytics Settings
analytics:
  google:
    id: G-1PEDJLM5JE

# avatar on sidebar
avatar: /assets/img/favicons/apple-touch-icon.png

toc: true

comments:
  provider: # [disqus | utterances | giscus]

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
